### ISSUE TITLE
How do I get settings in inspector.js?

### ISSUE THREAD

**Issue by developer-47** [elgatosf/streamdeck-plugin-template#14]
I'm almost done with my first plugin, but there's still an issue:

When I close and reopen the Property Inspector, the data from the input fields obviously disappears. 

I allready can get the settings in the app.js, when I open the Property inspector, via the onPropertyInspectorDidAppear method:

`myAction.onPropertyInspectorDidAppear(({action, context, device, event}) => {
    $SD.getSettings(context);
});`

`$SD.onDidReceiveSettings('de.nas-max.test.action', (jsn) => {
    console.log(jsn);
});`

So, how can I get the settings in the inspector.js, or how can I send a JSON element (in this context the settings) from app.js to inspector.js?

**Comment by ChekTek** [comment]
Hi @developer-47, as this is not really an issue with the template, it may be better to ask questions in our [GitHub Discussions](https://github.com/orgs/elgatosf/discussions) forum where the community can help.

To answer your question, you can take a look at the example property inspector code provided in the template: https://github.com/elgatosf/streamdeck-plugin-template/blob/main/src/com.elgato.template.sdPlugin/actions/template/property-inspector/inspector.js

The property inspector receives a `connected` event from Stream Deck which will include previously saved settings.

Hope this helps!
