### ISSUE TITLE
Translations not working at all

### ISSUE THREAD

**Issue by x7bit** [elgatosf/streamdeck-plugin-template#3]
The 'Localization' key/section inside the localization json doesn't work. This worked with the old pi-samples libraries, but not with the new ones.

```
{
 ....
  "Localization": {
    "More info": "More info",
    "Message": "Message",
    "Click Me": "Click Me",
    "Button": "Button"
  }
}
```

**Comment by tiptronic** [comment]
@x7bit  I added a localization script - but the snippet you posted won't do anything, because nothing changed from source (left) to target (right).

**Comment by tiptronic** [comment]
<img width="553" alt="CleanShot_2023-01-31_20 31 34" src="https://user-images.githubusercontent.com/80752/215863822-6ebc0a25-2679-4f66-b46d-8c2f6765dd92.png">

Not sure what you mean... I just copied your strings into an `es.json` and set my machine's language to spanish - and it works just fine... (using the script provided - that doesn't even need the `data-localize` tag to work).

As far as the `data-localize` tag is concerned, I'll take another look tomorrow...

**Comment by x7bit** [comment]
Sorry @tiptronic, my fault. In the `inspector.js` there is a comment that says:
```
/**
 * Provide window level functions to use in the external window
 * (this can be removed if the external window is not used)
 */
```
I thought that from there on down I could delete everything since my plugin has no external windows, and I had not noticed that the localization functions are at the bottom. I also thought that the form localization was something inherent to the library. Anyway, sorry for the misunderstanding.

**Comment by tiptronic** [comment]
@x7bit np - we're working on something much better... so just keep your `[data-localize]`  attributes intact and standby a little ;)

**Comment by x7bit** [comment]
Thank you @tiptronic, I will stay tuned!
