### ISSUE TITLE
setGlobalSettings Not Working As Expected on Windows 11

### ISSUE THREAD

**Issue by muks198** [elgatosf/streamdeck-plugin-template#5]
Hi,

I am successfully using the setSettings / getSettings to save actions however I am unable to use the setGlobalSettings/getGlobalSettings in a similar manner. I can confirm that the onDidReceiveGlobalSettings event is being fired and there are no Streamdeck log entries (%AppData%/Elgato/StreamDeck/logs) that indicate the request was not accept.

Any help would be appreciated.

The following is an extract of the code I am using in the property inspector for the custom plugin:

```
const globalSettings = $PI.getGlobalSettings();
.
.
Utils.setFormValue(globalSettings, formGlobalSettings);
.
.
formGlobalSettings.addEventListener(
        'input',
        Utils.debounce(150, () => {
            const value = Utils.getFormValue(formGlobalSettings);
            $PI.setGlobalSettings(value);
        })
    );
```

Thanks in advance!
M.

**Comment by muks198** [comment]
Hey Andy,

Corrected the above - didn't have enough coffee when I created this...

Below is a mostly complete extract of the functionality focused around the get/set global settings. Its being called from within the onConnected event handler in the property inspector for the action. The action specific settings (set/getSettings) work fine and I am using the JS lib from here: https://github.com/elgatosf/streamdeck-javascript-sdk/tree/e69b5c92e4316ae6b57d634e9f378fa9eef26274 

```
/// <reference path="../../libs/js/property-inspector.js" />
/// <reference path="../../libs/js/utils.js" />

const formGlobalSettings = document.querySelector('#property-global-settings');
const formActionSettings = document.querySelector('#property-action-settings');

$PI.onConnected((jsn) => {
    const {actionInfo, appInfo, connection, messageType, port, uuid} = jsn;
    const {payload, context} = actionInfo;
    const globalSettings = $PI.getGlobalSettings();
    const {settings} = payload;

    Utils.setFormValue(globalSettings, formGlobalSettings);
   
    formGlobalSettings.addEventListener(
        'input',
        Utils.debounce(150, () => {
            const value = Utils.getFormValue(formGlobalSettings);
            $PI.setGlobalSettings(value);
        })
    );
```

**Comment by tiptronic** [comment]
Hi @muks198 
you can drink as much coffee as you like, but it will not make it happen as you tried :) 

`getGlobalSettings` doesn't have a return value - it's an async process like 'Please Stream Deck, send me global settings'
SD then sends another callback to `didReceiveGlobalSettings` containing the settings. Here's a quick overview:

```
$PI.onConnected((jsn) => {
   ...
    $PI.getGlobalSettings();
   ...
 });

$PI.on('didReceiveGlobalSettings', jsn => {
  // here's your settings:
    console.log('****** didReceiveGlobalSettings', jsn?.payload?.settings);
});

```

I hope that clarifies things for you...
